# Docker Compose for FREDDY - Essential Infrastructure Services
# Low power server handling core services: reverse proxy, auth, DNS, home automation

# Named volumes for data/cache/databases only
volumes:
  # Application Data (persistent but not config)
  nginx_cache:
  nginx_logs:
  
  # Database volumes
  mysql_data:
  redis_data:
  
  # System volumes
  pihole_data:
  pihole_dnsmasq_data:
  homeassistant_data:
  syncthing_data:

# Custom networks for service isolation
networks:
  frontend:
    driver: bridge
  database:
    driver: bridge
  utilities:
    driver: bridge

services:
  # =============================================================================
  # FRONTEND SERVICES
  # =============================================================================

  # nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: nginx
    networks:
      - frontend
    environment:
      - TZ=${TZ:-America/Toronto}
    volumes:
      # CONFIG: Git-managed configuration files
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/mime.types:/etc/nginx/mime.types:ro
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./config/nginx/includes:/etc/nginx/includes:ro
      - ./config/nginx/html:/usr/share/nginx/html:ro
      - ./config/nginx/certs:/etc/nginx/ssl:ro
      # DATA: Logs and cache (not in Git)
      - nginx_logs:/var/log/nginx
      - nginx_cache:/var/cache/nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always

  # authelia - single sign-on authentication
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    networks:
      - frontend
      - database
    environment:
      - TZ=${TZ:-America/Toronto}
    volumes:
      # CONFIG: Git-managed configuration
      - ./config/authelia:/config
    ports:
      - "9091:9091"
    depends_on:
      - mysql
      - redis
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  # =============================================================================
  # SYSTEM SERVICES
  # =============================================================================

  # home assistant (requires host network for device discovery)
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    privileged: true
    network_mode: host
    environment:
      - TZ=${TZ:-America/Toronto}
    volumes:
      # CONFIG: Git-managed configuration
      - ./config/homeassistant:/config
      # DATA: Application data and history
      - homeassistant_data:/data
      # SYSTEM: Required for host access
      - /etc/localtime:/etc/localtime:ro
    restart: always

  # pi-hole - local dns server + ad blocker
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      - utilities
    environment:
      TZ: ${TZ:-America/Toronto}
      DNS1: ${PIHOLE_DNS1:-1.1.1.1}
      DNS2: ${PIHOLE_DNS2:-8.8.8.8}
      PIHOLE_DNS_: 'local'
      DHCP_ACTIVE: 'false'
      IPv6: 'false'
      WEB_PORT: '80'
      PIHOLE_UID: ${PUID:-1000}
      PIHOLE_GID: ${PGID:-1000}
      FTLCONF_LOCAL_IPV4: '0.0.0.0'
      WEBPASSWORD: ${PIHOLE_PASSWORD}
    volumes:
      # CONFIG: Git-managed configuration
      - ./config/pihole:/etc/pihole/config:ro
      # DATA: DNS records and logs
      - pihole_data:/etc/pihole
      - pihole_dnsmasq_data:/etc/dnsmasq.d
    ports:
      - "8053:80"
    #  - "53:53/tcp"
    #  - "53:53/udp"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  # syncthing - file synchronization
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    networks:
      - utilities
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/Toronto}
    volumes:
      # CONFIG: Git-managed configuration
      - ./config/syncthing:/config
      # DATA: Application data
      - syncthing_data:/data
      # SYNC: Directories to sync
      - ${SYNCTHING_DATA_PATH:-/home/syncthing}:/sync
    ports:
      - "8384:8384"
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "21027:21027/udp"
    restart: always

  # =============================================================================
  # DATABASE SERVICES
  # =============================================================================

  # mysql - for authelia storage
  mysql:
    image: mysql:8.0
    container_name: mysql
    networks:
      - database
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-authelia}
      - MYSQL_USER=${MYSQL_USER:-authelia}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TZ:-America/Toronto}
    volumes:
      # CONFIG: Git-managed configuration
      - ./config/mysql:/etc/mysql/conf.d:ro
      # DATA: Database files
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

  # redis - for authelia sessions
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - database
    environment:
      - TZ=${TZ:-America/Toronto}
    volumes:
      # CONFIG: Git-managed configuration
      - ./config/redis:/etc/redis:ro
      # DATA: Redis data files
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}

  # =============================================================================
  # MONITORING SERVICES
  # =============================================================================

  # watchtower - automatic container updates
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    environment:
      - TZ=${TZ:-America/Toronto}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=86400
      - WATCHTOWER_ROLLING_RESTART=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_REVIVE_STOPPED=false
      - WATCHTOWER_SCHEDULE=${WATCHTOWER_SCHEDULE:-0 2 * * *}
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_NOTIFICATION_URL}
    volumes:
      # CONFIG: Git-managed configuration
      - ./config/watchtower:/config:ro
      # SYSTEM: Required for Docker management
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  # datadog agent - monitoring and observability
  datadog:
    image: gcr.io/datadoghq/agent:7
    container_name: datadog-agent
    environment:
      - TZ=${TZ:-America/Toronto}
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=${DD_SITE:-datadoghq.com}
      - DD_HOSTNAME=${DD_HOSTNAME:-freddy-server}
      - DD_TAGS=${DD_TAGS:-env:homelab,service:web-server}
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_CONTAINER_EXCLUDE="name:datadog-agent"
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_AC_EXCLUDE="name:datadog-agent"
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    volumes:
      # CONFIG: Git-managed configuration
      - ./config/datadog:/etc/datadog-agent/conf.d:ro
      # DATA: Agent data
      #- datadog_data:/opt/datadog-agent/run
      # SYSTEM: Required for monitoring
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  # PHP-FPM for dashboard API processing
  php-fpm:
    image: php:8.2-fpm-alpine
    container_name: php-fpm
    networks:
      - frontend
    environment:
      - TZ=${TZ:-America/Toronto}
    volumes:
      # CONFIG: Web root with your HTML and PHP files
      - ./config/nginx/html:/usr/share/nginx/html
      # CACHE: Directory for PHP session data and cache
      - php_cache:/var/lib/php/sessions
      - php_opcache:/tmp
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    # Install additional PHP extensions if needed
    command: >
      sh -c "
        apk add --no-cache curl &&
        docker-php-ext-install json &&
        php-fpm
      "

  # Update nginx to connect to PHP-FPM
  nginx:
    image: nginx:alpine
    container_name: nginx
    networks:
      - frontend
    environment:
      - TZ=${TZ:-America/Toronto}
    volumes:
      # CONFIG: Git-managed configuration files
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/mime.types:/etc/nginx/mime.types:ro
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./config/nginx/includes:/etc/nginx/includes:ro
      - ./config/nginx/html:/usr/share/nginx/html:ro  # Note: not read-only for PHP
      - ./config/nginx/certs:/etc/nginx/ssl:ro
      # DATA: Logs and cache (not in Git)
      - nginx_logs:/var/log/nginx
      - nginx_cache:/var/cache/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm  # Ensure PHP-FPM starts before nginx
    restart: always

# Add volumes for PHP cache
volumes:
  # ... your existing volumes ...
  php_cache:
  php_opcache:

# Alternative: If you want to use a more full-featured PHP setup
# php-fpm-extended:
#   image: php:8.2-fpm-alpine
#   container_name: php-fpm
#   networks:
#     - frontend
#   environment:
#     - TZ=${TZ:-America/Toronto}
#   volumes:
#     - ./config/nginx/html:/usr/share/nginx/html
#     - php_cache:/var/lib/php/sessions
#   restart: always
#   command: >
#     sh -c "
#       apk add --no-cache curl git zip unzip &&
#       docker-php-ext-install json pdo pdo_mysql mysqli &&
#       curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
#       php-fpm
#     "